
services:

  backend_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: schoolmanagement_backend
    restart: always
    ports:
      - "5000:8080" # Map host 5000 to container 8080
    depends_on:
      - postgres
      - pgadmin
    environment:
      DB_HOST: postgres


  postgres:
    image: postgres:16
    container_name: schoolmanagement_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: school_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:8
    container_name: schoolmanagement_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

